math {
	let sin = 0

	sin8(x) {
		[math::sin + (x & 0xFF)]
	}

	init_sin8() {
		// TODO: Don't allocate, just load ROM sin8 data table.
		mem::init_allocator()
		math::sin = mem::allocate(256)
		[math::sin + 0] = 128
		[math::sin + 1] = 131
		[math::sin + 2] = 134
		[math::sin + 3] = 137
		[math::sin + 4] = 140
		[math::sin + 5] = 143
		[math::sin + 6] = 146
		[math::sin + 7] = 149
		[math::sin + 8] = 152
		[math::sin + 9] = 155
		[math::sin + 10] = 158
		[math::sin + 11] = 162
		[math::sin + 12] = 165
		[math::sin + 13] = 167
		[math::sin + 14] = 170
		[math::sin + 15] = 173
		[math::sin + 16] = 176
		[math::sin + 17] = 179
		[math::sin + 18] = 182
		[math::sin + 19] = 185
		[math::sin + 20] = 188
		[math::sin + 21] = 190
		[math::sin + 22] = 193
		[math::sin + 23] = 196
		[math::sin + 24] = 198
		[math::sin + 25] = 201
		[math::sin + 26] = 203
		[math::sin + 27] = 206
		[math::sin + 28] = 208
		[math::sin + 29] = 211
		[math::sin + 30] = 213
		[math::sin + 31] = 215
		[math::sin + 32] = 218
		[math::sin + 33] = 220
		[math::sin + 34] = 222
		[math::sin + 35] = 224
		[math::sin + 36] = 226
		[math::sin + 37] = 228
		[math::sin + 38] = 230
		[math::sin + 39] = 232
		[math::sin + 40] = 234
		[math::sin + 41] = 235
		[math::sin + 42] = 237
		[math::sin + 43] = 238
		[math::sin + 44] = 240
		[math::sin + 45] = 241
		[math::sin + 46] = 243
		[math::sin + 47] = 244
		[math::sin + 48] = 245
		[math::sin + 49] = 246
		[math::sin + 50] = 248
		[math::sin + 51] = 249
		[math::sin + 52] = 250
		[math::sin + 53] = 250
		[math::sin + 54] = 251
		[math::sin + 55] = 252
		[math::sin + 56] = 253
		[math::sin + 57] = 253
		[math::sin + 58] = 254
		[math::sin + 59] = 254
		[math::sin + 60] = 254
		[math::sin + 61] = 255
		[math::sin + 62] = 255
		[math::sin + 63] = 255
		[math::sin + 64] = 255
		[math::sin + 65] = 255
		[math::sin + 66] = 255
		[math::sin + 67] = 255
		[math::sin + 68] = 254
		[math::sin + 69] = 254
		[math::sin + 70] = 254
		[math::sin + 71] = 253
		[math::sin + 72] = 253
		[math::sin + 73] = 252
		[math::sin + 74] = 251
		[math::sin + 75] = 250
		[math::sin + 76] = 250
		[math::sin + 77] = 249
		[math::sin + 78] = 248
		[math::sin + 79] = 246
		[math::sin + 80] = 245
		[math::sin + 81] = 244
		[math::sin + 82] = 243
		[math::sin + 83] = 241
		[math::sin + 84] = 240
		[math::sin + 85] = 238
		[math::sin + 86] = 237
		[math::sin + 87] = 235
		[math::sin + 88] = 234
		[math::sin + 89] = 232
		[math::sin + 90] = 230
		[math::sin + 91] = 228
		[math::sin + 92] = 226
		[math::sin + 93] = 224
		[math::sin + 94] = 222
		[math::sin + 95] = 220
		[math::sin + 96] = 218
		[math::sin + 97] = 215
		[math::sin + 98] = 213
		[math::sin + 99] = 211
		[math::sin + 100] = 208
		[math::sin + 101] = 206
		[math::sin + 102] = 203
		[math::sin + 103] = 201
		[math::sin + 104] = 198
		[math::sin + 105] = 196
		[math::sin + 106] = 193
		[math::sin + 107] = 190
		[math::sin + 108] = 188
		[math::sin + 109] = 185
		[math::sin + 110] = 182
		[math::sin + 111] = 179
		[math::sin + 112] = 176
		[math::sin + 113] = 173
		[math::sin + 114] = 170
		[math::sin + 115] = 167
		[math::sin + 116] = 165
		[math::sin + 117] = 162
		[math::sin + 118] = 158
		[math::sin + 119] = 155
		[math::sin + 120] = 152
		[math::sin + 121] = 149
		[math::sin + 122] = 146
		[math::sin + 123] = 143
		[math::sin + 124] = 140
		[math::sin + 125] = 137
		[math::sin + 126] = 134
		[math::sin + 127] = 131
		[math::sin + 128] = 127
		[math::sin + 129] = 124
		[math::sin + 130] = 121
		[math::sin + 131] = 118
		[math::sin + 132] = 115
		[math::sin + 133] = 112
		[math::sin + 134] = 109
		[math::sin + 135] = 106
		[math::sin + 136] = 103
		[math::sin + 137] = 100
		[math::sin + 138] = 97
		[math::sin + 139] = 93
		[math::sin + 140] = 90
		[math::sin + 141] = 88
		[math::sin + 142] = 85
		[math::sin + 143] = 82
		[math::sin + 144] = 79
		[math::sin + 145] = 76
		[math::sin + 146] = 73
		[math::sin + 147] = 70
		[math::sin + 148] = 67
		[math::sin + 149] = 65
		[math::sin + 150] = 62
		[math::sin + 151] = 59
		[math::sin + 152] = 57
		[math::sin + 153] = 54
		[math::sin + 154] = 52
		[math::sin + 155] = 49
		[math::sin + 156] = 47
		[math::sin + 157] = 44
		[math::sin + 158] = 42
		[math::sin + 159] = 40
		[math::sin + 160] = 37
		[math::sin + 161] = 35
		[math::sin + 162] = 33
		[math::sin + 163] = 31
		[math::sin + 164] = 29
		[math::sin + 165] = 27
		[math::sin + 166] = 25
		[math::sin + 167] = 23
		[math::sin + 168] = 21
		[math::sin + 169] = 20
		[math::sin + 170] = 18
		[math::sin + 171] = 17
		[math::sin + 172] = 15
		[math::sin + 173] = 14
		[math::sin + 174] = 12
		[math::sin + 175] = 11
		[math::sin + 176] = 10
		[math::sin + 177] = 9
		[math::sin + 178] = 7
		[math::sin + 179] = 6
		[math::sin + 180] = 5
		[math::sin + 181] = 5
		[math::sin + 182] = 4
		[math::sin + 183] = 3
		[math::sin + 184] = 2
		[math::sin + 185] = 2
		[math::sin + 186] = 1
		[math::sin + 187] = 1
		[math::sin + 188] = 1
		[math::sin + 189] = 0
		[math::sin + 190] = 0
		[math::sin + 191] = 0
		[math::sin + 192] = 0
		[math::sin + 193] = 0
		[math::sin + 194] = 0
		[math::sin + 195] = 0
		[math::sin + 196] = 1
		[math::sin + 197] = 1
		[math::sin + 198] = 1
		[math::sin + 199] = 2
		[math::sin + 200] = 2
		[math::sin + 201] = 3
		[math::sin + 202] = 4
		[math::sin + 203] = 5
		[math::sin + 204] = 5
		[math::sin + 205] = 6
		[math::sin + 206] = 7
		[math::sin + 207] = 9
		[math::sin + 208] = 10
		[math::sin + 209] = 11
		[math::sin + 210] = 12
		[math::sin + 211] = 14
		[math::sin + 212] = 15
		[math::sin + 213] = 17
		[math::sin + 214] = 18
		[math::sin + 215] = 20
		[math::sin + 216] = 21
		[math::sin + 217] = 23
		[math::sin + 218] = 25
		[math::sin + 219] = 27
		[math::sin + 220] = 29
		[math::sin + 221] = 31
		[math::sin + 222] = 33
		[math::sin + 223] = 35
		[math::sin + 224] = 37
		[math::sin + 225] = 40
		[math::sin + 226] = 42
		[math::sin + 227] = 44
		[math::sin + 228] = 47
		[math::sin + 229] = 49
		[math::sin + 230] = 52
		[math::sin + 231] = 54
		[math::sin + 232] = 57
		[math::sin + 233] = 59
		[math::sin + 234] = 62
		[math::sin + 235] = 65
		[math::sin + 236] = 67
		[math::sin + 237] = 70
		[math::sin + 238] = 73
		[math::sin + 239] = 76
		[math::sin + 240] = 79
		[math::sin + 241] = 82
		[math::sin + 242] = 85
		[math::sin + 243] = 88
		[math::sin + 244] = 90
		[math::sin + 245] = 93
		[math::sin + 246] = 97
		[math::sin + 247] = 100
		[math::sin + 248] = 103
		[math::sin + 249] = 106
		[math::sin + 250] = 109
		[math::sin + 251] = 112
		[math::sin + 252] = 115
		[math::sin + 253] = 118
		[math::sin + 254] = 121
		[math::sin + 255] = 124
	}
}

/// Return quotient and remainder of division
div_mod(dividend, divisor) {
	let q = 0
	let r = 0
	let i = 24
	while i > 0 {
		r = r << 1 | (dividend >> (i - 1) & 1)
		if r >= divisor {
			r = r - divisor
			q = q | (1 << (i - 1))
		}
		i = i - 1
	}
	q, r
}

/// Return quotient and remainder of division
// TODO: Remove off-by-one errors
// div_mod(numerator, denominator) asm {
// 	ld   r4, rB, 3 ; denominator
// 	ld   r3, rB, 0 ; numerator
// 	let  r1, 0     ; quotient
// 	let  r2, 0     ; remainder
// 	let  r5, 24     ; i = bits to go through (up to 24)
// 	.while_i: ; i != 0
// 		shl  r2, 1
// 		shr  rD, r3, r5
// 		and  rD, 1
// 		or   r2, r2, rD
// 		less rD, r2, r4
// 		if   rD, .next
// 			sub  r2, r2, r4
// 			let  rD, 1
// 			shl  rD, rD, r5
// 			or   r1, r1, rD
// 		.next:
// 			sub  r5, 1
// 			if   r5, .while_i
// }

// uint pcg_hash(uint input)
// {
//     uint state = input * 747796405u + 2891336453u;
//     uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
//     return (word >> 22u) ^ word;
// }

hash(input) {
	let state = input * 0b100100100111011110110101 + 0b010101100100101100000101
	let word = ((state >> ((state >> 20) + 4)) ^ state) * 0b100011101111001011011001
	(word >> 14) ^ word
}